---
- hosts: all
  become: true 
  tasks:
    - name: Install appache httpd server
      ansible.builtin.apt:
       name: apache2
       state: present
       update_cache: yes
    - name: Copy file from loacl to remote
      ansible.builtin.copy:
       src: index.html
       dest: /var/www/html
       owner: root
       group: root
       mode: '0644'     
